### ISSUE TITLE
Set up mini-tutorial and help pages

### ISSUE THREAD

**Issue by fsteeg** [spinfo/drc#100]
Screen cast?

_Original author: [claesn](http://github.com/claesn), 2010-03-14, at fsteeg/drc#46_

**Comment by fsteeg** [comment]
Need meaningful term for 'OCR' - ANDP uses 'electronically translated text'.

_Original author: [claesn](http://github.com/claesn), 2010-03-14, at fsteeg/drc#46_

**Comment by fsteeg** [comment]
We should probably set up an integrated user guide as Eclipse help pages (can be generated from wiki markup)

**Comment by claesn** [comment]
Integrated as FAQ in portal
