### ISSUE TITLE
Display no suggestions if distance is too far

### ISSUE THREAD

**Issue by fsteeg** [spinfo/drc#146]

**Comment by fsteeg** [comment]
Remove suggestions where distance is more than half the length of the word (closed by e837c611a9e331e8b3961893eaca87bd5e046993)

**Comment by claesn** [comment]
Works fine. Possible extension: Should we also consider the length of computed suggestions (e.g. do not display suggestions, that are significantly shorter or longer - example: one of the suggestions for "niebels" is "danievensi", which has 3 more letters than the original word)?

**Comment by fsteeg** [comment]
Created new issue (#210)
