### ISSUE TITLE
Change closing threshold to 2, reopen on downvote

### ISSUE THREAD

**Issue by fsteeg** [spinfo/drc#157]

**Comment by fsteeg** [comment]
Tweaked word locking criteria (closed by 81791155648274def898ac99e8e9eb26aaeafe96)

**Comment by claesn** [comment]
Problems with threshold computation: Votes are no longer stored in page-level xml, but in user-xmls only. Therefore no shutdown by upvotes and no reopen on downvote possible.

**Comment by fsteeg** [comment]
New issue opened for lost votes: #189
