### ISSUE TITLE
Are you sure question on dubious edits

### ISSUE THREAD

**Issue by fsteeg** [spinfo/drc#158]

**Comment by fsteeg** [comment]
Are you sure question on dubious edits (closed by 60ee6361fb1a29da705f4c8759e10ed6104b4206)

**Comment by claesn** [comment]
Works fine so far, but should not be thrown after a change was explicitly accepted. Maybe if the wordlength comparison was always done on the actual wordform, not the original one, the message wouldn't be thrown every time a user skips through.

**Comment by fsteeg** [comment]
Compare with latest form in history when checking dubious edits (closed by bac76bdb885b555f606d9077b17d25826c488438)
