### ISSUE TITLE
Chapter navigation

### ISSUE THREAD

**Issue by fsteeg** [spinfo/drc#177]
Depends on #183

Requires usage of metadata files.

**Comment by fsteeg** [comment]
Moved metadata to DB (closed by 5f2d4fb222a93e06912ad1ac7990ad6c27ca991c)

**Comment by claesn** [comment]
Mapping (see #183) seems to be incorrect (wrong by -6 pages in "band 4", "band 8", "band 9", -20 pages in "band11", -18 in "band17", etc.)

**Comment by fsteeg** [comment]
Fixed chapter mapping (closed by 0f777f205428504810d885fe778c784d8c545bcc, closed by 0f777f205428504810d885fe778c784d8c545bcc)
