### ISSUE TITLE
Mapping of PDF page numbers to original TIFF numbers for metadata usage

### ISSUE THREAD

**Issue by fsteeg** [spinfo/drc#183]
Blocks #177

**Comment by fsteeg** [comment]
Fixed by using original file names (matana).

**Comment by claesn** [comment]
Unclear if correct - #177 doesn't work properly, seems to be because of incorrect mapping.

**Comment by fsteeg** [comment]
Fixed chapter mapping (closed by 0f777f205428504810d885fe778c784d8c545bcc, closed by 0f777f205428504810d885fe778c784d8c545bcc)
