### ISSUE TITLE
Edit suggestions should be based on most recent form

### ISSUE THREAD

**Issue by fsteeg** [spinfo/drc#187]
And no suggestions for closed words

**Comment by fsteeg** [comment]
Use latest form to compute edit suggestions (closed by e3d9cf1bdda0770026ee3c324283cafd619f4cdd)

**Comment by claesn** [comment]
works fine. General remark: In some cases special characters in edit suggestions are not correctly displayed (example: pasch with "long s").

**Comment by fsteeg** [comment]
Created new issue (#209)
