### ISSUE TITLE
Search in comments

### ISSUE THREAD

**Issue by fsteeg** [spinfo/drc#194]

**Comment by fsteeg** [comment]
Search in comments (closed by a17b33cee8a90c856cfd2458f320b92ef5850a93)

**Comment by claesn** [comment]
works fine, but switching "search-space" (in drop down menu) is very slow

**Comment by claesn** [comment]
should comments be shown in result list (e.g. like tags)?
alternatively just a hint like "there are comments to this page" or "see page comments view"?

**Comment by fsteeg** [comment]
Created new issue for additional functionality (#208)
