### ISSUE TITLE
Unable to save without focus in edit part

### ISSUE THREAD

**Issue by matana** [spinfo/drc#200]
Unable to save without focus in edit part

**Comment by fsteeg** [comment]
No longer a problem (we were losing focus before).

**Comment by claesn** [comment]
Problem reappeared in windows-version of beta2 (2011-02-25).

**Comment by matana** [comment]
@claesn: I need more details to reconstruct the problem.

**Comment by matana** [comment]
See: Issue #296
The context for the key bindings is active for the whole perspective. Even focus loss in edit part should not affect the save action.
