### ISSUE TITLE
Faulty coordinates in higher volumes

### ISSUE THREAD

**Issue by fsteeg** [spinfo/drc#205]
In most additional volumes the coordinates are more or less off. They seem to high in the upper area of pages, and too low in the lower areas. Also, they seem to get worse in higher volumes. A possibly related issue: some pages are tilted. Perhaps we have some wrong JPG files or something.

**Comment by matana** [comment]
Faulty coordinates were produced from corrupt scaling of the images. The Application uses now PNGs with there original size. The Scaling of the images is handled by the UI. Closed by c79e521510cf89f90f170acd8a481365ad126801

**Comment by claesn** [comment]
Vol. 4 - 27 seem to be OK now, except - for unknown reasons - single pages here and there (e.g. page 485 in Vol. 18).
Vol. 30, 33, 35, 36, 37, 38 not yet updated.

**Comment by claesn** [comment]
Vol. 30-38 look OK, too - some problems with single pages remain.
