### ISSUE TITLE
Enable and test P2 updates on Mac and Windows

### ISSUE THREAD

**Issue by fsteeg** [spinfo/drc#211]

**Comment by fsteeg** [comment]
Tweaked target definition and product, enabled p2 updates (closed by ac998ac0c2bd87c911c2938c327f84f5750aeb84)

**Comment by fsteeg** [comment]
We currently can't update from nightly builds on Mac, because we cannot build for Mac on Hydra. Local builds (on Mac OS) work, so we could manually upload updates to Hydra, which should then allow updating. Windows should be fine.

**Comment by claesn** [comment]
OK on Windows

**Comment by fsteeg** [comment]
Works on Mac in principle, but we need an automated build process.

**Comment by fsteeg** [comment]
Mac builds now active on bob.spinfo.uni-koeln.de:
- http://bob.spinfo.uni-koeln.de/downloads/master/
- http://bob.spinfo.uni-koeln.de/p2/ (used by editor)
