### ISSUE TITLE
Empty words cannot be up- or downvoted

### ISSUE THREAD

**Issue by fsteeg** [spinfo/drc#218]

**Comment by fsteeg** [comment]
Fixed issues with empty words (closed by 2dd256a195bd97efa5546650f6e01762340c640d)

**Comment by claesn** [comment]
Does not work for Windows - but seems to be a minor problem, since reverting is possible.

**Comment by claesn** [comment]
But a new problem occurs, because the word length is changed - when asked to save the edit, saving is not possible - and no further editing, since page cannot be changed without saving (image and text remain in windows)

**Comment by claesn** [comment]
Problem described in last comment occurs only if revert or new edit is done by different user - i.e. it works only if correction of empty word is changed by same user.

**Comment by fsteeg** [comment]
Fixed issue when reverting to previous modification after downvoting current (closed by a5ed500db93d9276dd563063a85a63fe1fa55d08)
