### ISSUE TITLE
Chapter "Nachträge" in Vol. 4 not displayed

### ISSUE THREAD

**Issue by claesn** [spinfo/drc#261]
Page 1035ff

**Comment by fsteeg** [comment]
Not sure about the issue here - Nachträge seems correct (1005-1019 both in editor and book).

**Comment by claesn** [comment]
Was a bit confusing: Comment originally referred to 4th volume (now: Vol. II,2.-3.), not Vol.4.
In Vol. II,2.-3. pp 1035ff should appear as separate chapter "Nachträge" (containing Märchen, Sagen, Sprichwörter, etc) - currently listed as part of "Chapter X: Titelblatt".
But in Vol IV there's also a little bug: Nachträge is correct, "Chapter X: Unknown" has duplicate page numbers and should be split into separate chapters for "Einleitung" and "Inhalt"
