### ISSUE TITLE
Sometimes a page loads with wrong encoding

### ISSUE THREAD

**Issue by fsteeg** [spinfo/drc#288]
Steps to reproduce:
- In the editor, search for 'reformada' in tags, on hydra1 data
- Open chapter, text summary has wrong encoding
- Select page, text has wrong encoding, reloads after a moment with correct encoding

**Comment by matana** [comment]
I can not reproduce the bug neither in RAP nor in RCP application. Encoding seems to be correct.

**Comment by fsteeg** [comment]
Looks good here too, closing.
