### ISSUE TITLE
Test merged RAP and RCP apps

### ISSUE THREAD

**Issue by fsteeg** [spinfo/drc#304]

**Comment by fsteeg** [comment]
Test deployment of RAP version running at:
http://hydra2.spinfo.uni-koeln.de:7777/drc/drc_rap?startup=de.uni_koeln.ub.drc.ui.rap.entrypoint

Test builds of RCP version available from:
http://hydra2.spinfo.uni-koeln.de/downloads/nightlies/

**Comment by claesn** [comment]
Current testing at:
http://bob.spinfo.uni-koeln.de:8181/drc/drc_rap?startup=de.uni_koeln.ub.drc.ui.rap.entrypoint

portal at:

http://bob.spinfo.uni-koeln.de:9000/

RCP:

http://bob.spinfo.uni-koeln.de/downloads/master/
