### ISSUE TITLE
Implement internationalization

### ISSUE THREAD

**Issue by fsteeg** [spinfo/drc#98]
_Original author: [fsteeg](http://github.com/fsteeg), 2009-12-23, at fsteeg/drc#16_

**Comment by fsteeg** [comment]
See https://bugs.eclipse.org/bugs/show_bug.cgi?id=306576

**Comment by fsteeg** [comment]
Internationalization, German and partial Romansch localization (closed by 7baf2ce04cb514e8cbd3abeb3dba87b5fb4114c9)

**Comment by claesn** [comment]
Some translations missing.
